### ISSUE TITLE
AWS Integration that doesn't use edda

### ISSUE THREAD

**Issue by emjburns** [spinnaker/swabbie#175]
Netflix uses edda to fetch amazon data: https://github.com/spinnaker/swabbie/blob/master/swabbie-aws/src/main/kotlin/com/netflix/spinnaker/swabbie/aws/edda/EddaService.kt

We need to provide a configurable way to get this information from amazon (from many accounts, not just the account swabbie is running in) so that edda is not a requirement.

**Comment by jeyrschabu** [comment]
Done
