### ISSUE TITLE
mark endpoint should be expandable

### ISSUE THREAD

**Issue by jeyrschabu** [spinnaker/swabbie#96]
- Let's add an `expand`  query param. By default we will return just a list of ids. When expend= true we return the full body. I suspect that list will grow so we should think about paginating results

**Comment by emjburns** [comment]
Implemented in part in https://github.com/spinnaker/swabbie/pull/100

Right now the endpoint returns the everything but the actual resource body until you put `?expand=true`. Will slim that down further if I see problems with the number of results.
